[package]
name = "ff"
version = "0.1.0"
edition = "2024"
license = "MIT"
default-run = "4f"

[[bin]]
name = "4f"
path = "src/main.rs"

[dependencies]
iced = { version = "0.14", features = ["tokio"] }
